### ISSUE TITLE
Don't blow away uncommitted changes

### ISSUE THREAD

**Issue by robinbowes** [voxpupuli/modulesync#87]
I just managed to blow away all the uncommitted changes on a local feature branch with modulesync.

Surely it should detect uncommitted changes and abort rather than just dropping them so it can checkout the modulesync branch?

R.

**Comment by james-powis** [comment]
howdy robin, if you reference some of the documentation in modulesync_configs and modulesync typically running msync is done from outside of the typical working directory this ensures the msync does not conflict with any work in progress. 

My personal workflow is this:
live development in: `~/git/my_funky_project`
modulesync_configs in: `~/git/modulesync_configs`

```bash
cd ~/git/modulesync_configs
msync update -f my_funky_project
```

I also highly recommend configuring a modulesync.yml file documented here: https://github.com/voxpupuli/modulesync

Reference the one used by voxpupuli:
```yaml
---
git_base: 'git@github.com:'
namespace: voxpupuli
branch: modulesync
message: "Update from voxpupuli modulesync_config"
...
# vim: syntax=yaml
```

Hopefully this is helpful.
