### ISSUE TITLE
allow setting a tree as `unmanaged`

### ISSUE THREAD

**Issue by igalic** [voxpupuli/modulesync#89]
Currently, in order to disable acceptance tests boilerplate, this is the configuration needed:
```yaml
spec/acceptance/nodesets/debian-78-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-66-x64-pe.yml:
  unmanaged: true
spec/acceptance/nodesets/debian-82-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-511-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-66-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/debian-8.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/debian-7.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/ubuntu-14.04.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/centos-6.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/ubuntu-16.04.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/centos-5.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/ubuntu-12.04.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/centos-7.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1604-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1204-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-72-x64.yml:
  unmanaged: true
```

to my shame, a lot of modules don't have acceptance tests, and, yet, i'd still like to be able to use modulesync and @voxpupuli's configurations, because it's *really* convenient.
